[package]
name = "cross-platform-clipboard"
version = "0.1.0"
authors = ["evan <138378166+evanhgs@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
dioxus = { version = "0.7.1" }
directories = "6.0.0"
rusqlite = {version = "0.40.2", features = ["bundled"]}

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
