[package]
name = "cross-platform-clipboard"
version = "0.1.0"
authors = ["evan <138378166+evanhgs@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["desktop"] }
dioxus-logger = "0.7.10"
directories = "6.0.0"
anyhow = "1.0.104"
log = "0.4.34"
rusqlite = { version = "0.40.2", features = ["bundled"] }
tracing = "0.1.44"
arboard = "3.6.1"
base64 = "0.22.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
sha2 = "0.10.9"
tokio = { version = "1.53.1", features = ["time"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"

[profile.dev]
opt-level = 0
debug = 2
incremental = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
debug = 0
incremental = false
